### ISSUE TITLE
Package broken in version 1.1.0

### ISSUE THREAD

**Issue by tsvetomir** [DSchau/jest-preset-typescript#3]
Seems like the release for v1.1.0 (#2) went bad - the [jest-preset-typescript.js file is missing](https://unpkg.com/jest-preset-typescript@1.1.0/jest-preset-typescript.js) and [source files](https://unpkg.com/jest-preset-typescript@1.1.0/src/) are included instead.

**Comment by DSchau** [comment]
@tsvetomir fixed in 1.2.0 -> https://unpkg.com/jest-preset-typescript@1.2.0/jest-preset-typescript.js

Thanks!
